apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  labels:
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.name }}.{{ .Release.Namespace }}.gcp.devops.gdpdentsu.net
      http:
        paths:
          - path: / 
            backend:
              serviceName: {{ .Values.service.name }}
              servicePort: {{ .Values.service.externalPort }}
